[platformio]
default_envs = t3-v161-868

[env]
platform = espressif32@7.0.1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
    jgromes/RadioLib@7.7.1
    olikraus/U8g2@2.36.5
    adafruit/Adafruit BME280 Library@2.3.0
    adafruit/Adafruit Unified Sensor@1.1.15
    adafruit/Adafruit BusIO@1.17.4
    knolleary/PubSubClient@2.8.0
    https://github.com/christandlg/AS3935MI/archive/01ee19264742839414b11f701c4266ded948f033.zip
build_flags =
    -D CORE_DEBUG_LEVEL=1

; LILYGO/TTGO LoRa32 T3 V1.6.1 EU 868 MHz (SX1276/RFM95 family)
[env:t3-v161-868]
board = ttgo-lora32-v21
board_build.variant = ttgo-lora32-v21new
build_flags =
    ${env.build_flags}
    -D BOARD_T3_V16_SX1276=1

; LILYGO T3-S3 + SX1276/RFM95 EU 868 MHz
[env:t3-s3-868]
board = lilygo-t3-s3
build_flags =
    ${env.build_flags}
    -D BOARD_T3_S3_SX1276=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
