# 1
story += [h1('1. Scopo, ambito e stato del progetto','s1'),
          P('ESP32 Davis Weather Gateway e un gateway autonomo per ricevere direttamente una stazione Davis Vantage Pro2 / Pro2 Plus wireless europea mediante una scheda LILYGO/ESP32 con radio SX1276/RFM95 a 868 MHz. L\'obiettivo e sostituire il ruolo di ricezione e inoltro normalmente svolto da console o gateway commerciali, mantenendo pero una separazione chiara tra dati acquisiti via RF e misure locali del ricevitore.'),
          InfoBox('Stato della baseline', '<b>Firmware:</b> 0.2.0-dev. La compilazione CI e validata per i target T3 V1.6.1 e T3-S3. La parte RF e ancora in validazione sul campo contro hardware Davis reale; le conversioni non confermate sono indicate come tali.', 'info'),
          Spacer(1,3*mm),
          ArchDiagram(),
          P('Figura 1 - Architettura logica del sistema: la ISS trasmette i parametri esterni, mentre il gateway aggiunge la pressione locale tramite BME280 e pubblica i dati verso servizi locali o un endpoint HTTP.', 'Captionx'),
          h2('1.1 Cosa e coperto dalla versione 1.2'),
          bullets(['caratteristiche della sensor suite Davis e differenza fra Vantage Pro2 e Pro2 Plus;',
                   'caratteristiche ufficiali dei principali sensori e dei tempi di aggiornamento;',
                   'profilo radio europeo 868 MHz FHSS e strategia di ricezione del gateway;',
                   'struttura dei frame RF e decodifica implementata;',
                   'origine della pressione barometrica e ruolo del BME280 locale;',
                   'provisioning Wi-Fi, Web UI, persistenza NVS, upload HTTP e modello di sicurezza;',
                   'strumenti di diagnostica, limiti noti e piano di validazione su hardware reale.']),
          InfoBox('Classificazione delle informazioni', '<b>[D]</b> = dato ufficiale Davis; <b>[P]</b> = comportamento implementato nel progetto; <b>[R]</b> = informazione di interoperabilita/reverse engineering pubblico. Le tre categorie non vanno confuse.', 'ok'),
          PageBreak()]

# 2
story += [h1('2. Davis Vantage Pro2 e Pro2 Plus: stazione e sensor suite','s2'),
          P('La Wireless Vantage Pro2 Sensor Suite 6322/6322M comprende temperatura e umidita esterne, velocita e direzione del vento e pioggia. Davis dichiara aggiornamenti in tempo reale e una portata radio fino a 300 m in linea di vista. I sensori UV e radiazione solare sono opzionali sulla Pro2 e fanno parte delle configurazioni Pro2 Plus, come 6327/6327M. [D1][D2][D4]'),
          SensorDiagram(),
          P('Figura 2 - Mappa funzionale dei sensori supportati dal gateway. UV e solare dipendono dall\'allestimento della stazione.', 'Captionx'),
          h2('2.1 Famiglie di riferimento'),
          table([
              ['Famiglia','Sensor suite','Sensori principali','Note'],
              ['Vantage Pro2','6322 / 6322M','T/H esterni, vento, pioggia','Schermo passivo; UV/solare opzionali'],
              ['Vantage Pro2 fan-aspirated','6323 / 6323M','T/H esterni, vento, pioggia','Schermo ventilato 24 h'],
              ['Vantage Pro2 Plus','6327 / 6327M','T/H, vento, pioggia, UV, solare','Sensori radiometrici inclusi'],
              ['Vantage Pro2 Plus fan-aspirated','6328 / 6328M','T/H, vento, pioggia, UV, solare','Schermo ventilato 24 h'],
          ], [38*mm,34*mm,66*mm,CONTENT_W-138*mm]),
          Spacer(1,3*mm),
          h2('2.2 Alimentazione e costruzione della ISS'),
          P('La sensor suite wireless e alimentata a energia solare con batteria di backup. La specifica Davis indica per la parte ISS una cella al litio CR-123 da 3 V, con autonomia senza luce indicata fino a circa 8 mesi; la struttura usa materiali plastici resistenti ai raggi UV. Il campo operativo dichiarato per la sensor suite e da -40 a +65 °C. [D2]'),
          table([
              ['Caratteristica','Valore Davis'],
              ['Campo operativo ISS','-40 .. +65 °C'],
              ['Pannello solare ISS SIM','0,5 W'],
              ['Batteria di backup','CR-123, 3 V litio'],
              ['Cavo anemometro incluso','12 m; estensione raccomandata fino a 73 m con limiti alle alte velocita'],
              ['Corpo / materiali','ABS e polipropilene resistenti UV'],
          ], [58*mm,CONTENT_W-58*mm]),
          InfoBox('Nota di compatibilita', 'Il progetto non assume che ogni stazione abbia UV e solare. Il decoder puo ricevere questi packet type quando sono presenti; la Web UI deve mostrare <b>--</b> o valore non disponibile quando il sensore non esiste.', 'info'),
          PageBreak()]

# 3 sensor specs
story += [h1('3. Caratteristiche dei sensori e cadenza dei dati','s3'),
          P('La tabella seguente riassume le specifiche ufficiali piu rilevanti per il progetto. Gli intervalli indicati sono quelli dichiarati da Davis per visualizzazione/aggiornamento delle variabili e non coincidono necessariamente con la cadenza di ogni singolo frame RF. [D2]'),
          table([
              ['Parametro','Campo / risoluzione','Accuratezza','Aggiornamento Davis'],
              ['Temperatura esterna','-40 .. +65 °C; 0,1 °C nominale','±0,3 °C','10-12 s'],
              ['Umidita esterna','1 .. 100 %RH; 1 %','±2 %RH','50-60 s'],
              ['Velocita vento','0 .. 322 km/h','±3,2 km/h o ±5%','2,5-3 s'],
              ['Direzione vento','1 .. 360°','±3°','2,5-3 s'],
              ['Pioggia totale metric','0,2 mm per tip','±3% o 1 tip fino a 250 mm/h','20-24 s'],
              ['Rain rate','0 .. 762 mm/h; 0,1 mm/h','±5% fino a 250 mm/h','20-24 s'],
              ['Radiazione solare*','0 .. 1800 W/m2; 1 W/m2','±5% fondo scala','50-60 s (5 min buio)'],
              ['Indice UV*','0 .. 16; 0,1','±5% fondo scala','50-60 s (5 min buio)'],
          ], [38*mm,53*mm,48*mm,CONTENT_W-139*mm], font=7.1),
          P('* sensori presenti sulle versioni Plus o come opzioni compatibili.', 'Smallx'),
          h2('3.1 Temperatura e schermatura'),
          P('Il sensore di temperatura esterna e collocato nella ISS. Davis indica una accuratezza del sensore di ±0,3 °C. Con schermatura passiva puo comparire un errore radiativo fino a circa +2 °C in condizioni severe di sole e vento debole; la schermatura aspirata riduce sensibilmente tale effetto. [D2]'),
          h2('3.2 Pluviometro e rain rate'),
          P('La versione metrica usa un meccanismo a cucchiaio basculante da 0,2 mm per scatto. Davis calcola il rain rate dal tempo fra scatti successivi; oltre 15 minuti o con un solo scatto il rain rate viene considerato zero. Nel gateway il valore di mm per tip resta configurabile per adattarsi alla reale versione del collettore. [D2][P]'),
          h2('3.3 Vento'),
          P('L\'anemometro Davis usa un sensore magnetico per la velocita e una banderuola con potenziometro per la direzione. La velocita e misurata internamente in mph e poi convertita nelle altre unita; il progetto converte in km/h. [D2][P]'),
          h2('3.4 Sensori UV e solare'),
          P('Le versioni Pro2 Plus aggiungono UV e radiazione solare. Il sensore solare ha campo dichiarato 0-1800 W/m2; l\'indice UV 0-16. Entrambe le conversioni RF sono presenti nel decoder, ma la formula UV e marcata come da confermare sul campo con un riferimento Davis. [D2][R][P]'),
          PageBreak()]

# 4 pressure
story += [h1('4. Pressione barometrica: perche e lato ricevitore','s4'),
          InfoBox('Punto architetturale fondamentale', 'Per la <b>Wireless Vantage Pro2 Sensor Suite 6322/6322M</b> il barometro non e un sensore della ISS esterna. Davis elenca nella sensor suite T/H esterni, vento e pioggia. WeatherLink Live, invece, dichiara esplicitamente un barometro integrato insieme a temperatura e umidita interne. [D1][D3]', 'ok'),
          P('Questa separazione spiega perche il progetto non cerca un packet type RF di pressione nella ISS 6322/6322M. La pressione viene misurata localmente dal gateway con un BME280, replicando il principio funzionale dei ricevitori Davis.'),
          h2('4.1 Riduzione della pressione al livello del mare'),
          P('Il firmware applica una riduzione barometrica in funzione della quota configurata. La formula implementata e:'),
          Preformatted('P0 = Pstation / (1 - altitude_m / 44330) ^ 5.255', styles['Codex']),
          P('La quota deve essere corretta: Davis stessa richiede una buona accuratezza dell\'elevazione per ottenere una riduzione al livello del mare attendibile. La specifica della console tradizionale indica per il barometro un campo 540-1100 hPa e accuratezza complessiva di circa ±1 hPa a temperatura ambiente. [D2]'),
          h2('4.2 Installazione del BME280'),
          bullets(['montare il BME280 in comunicazione con la pressione ambiente, evitando contenitori completamente sigillati;',
                   'tenerlo lontano da regolatori, ESP32 e display che generano calore se si vogliono usare anche T/H locali;',
                   'configurare la quota reale dell\'installazione prima di confrontare la pressione ridotta con una console Davis;',
                   'non usare la temperatura del BME280 come temperatura esterna: quella resta un dato RF della ISS.']),
          InfoBox('Conseguenza per il protocollo', 'Nel documento RF, i packet type di temperatura, umidita, vento, pioggia, UV e solare appartengono al flusso ISS. La pressione e un dato <b>locale al ricevitore</b> e viene aggiunta al record di uscita dal gateway.', 'info'),
          PageBreak()]

# 5 RF
story += [h1('5. Segnale radio Davis EU e FHSS','s5'),
          P('La documentazione Davis indica per la regione EU un collegamento FHSS nella banda 868,0-868,6 MHz con potenza inferiore a 8 mW, fino a 8 ID trasmettitore selezionabili. La portata dichiarata e fino a 300 m in linea di vista e 60-120 m attraverso pareti, in condizioni dipendenti dall\'ambiente. [D2]'),
          table([
              ['Parametro','Davis / progetto'],
              ['Regione','EU'],
              ['Banda ufficiale','868,0 - 868,6 MHz FHSS [D]'],
              ['Potenza trasmettitore','< 8 mW [D]'],
              ['ID trasmettitore','8 codici selezionabili [D]'],
              ['Portata dichiarata','fino a 300 m LOS; 60-120 m attraverso pareti [D]'],
              ['Modulazione implementata','2-FSK [R/P]'],
              ['Bit rate','19,2 kbps [R/P]'],
              ['Deviazione','4,8 kHz [R/P]'],
              ['Shaping','Gaussian BT=0,5 [R/P]'],
              ['Sync','CB 89 [R/P]'],
              ['Pacchetto','10 byte fissi [R/P]'],
          ], [60*mm,CONTENT_W-60*mm]),
          h2('5.1 Hop set europeo implementato'),
          HopDiagram(),
          table([
              ['Hop','FRF','Frequenza'],
              ['1','D9 04 45','868.066711 MHz'],
              ['2','D9 13 04','868.297119 MHz'],
              ['3','D9 21 C2','868.527466 MHz'],
              ['4','D9 0B A4','868.181885 MHz'],
              ['5','D9 1A 63','868.412292 MHz'],
          ], [20*mm,45*mm,CONTENT_W-65*mm]),
          P('Le cinque frequenze sono parametri di interoperabilita derivati da lavori pubblici di reverse engineering e sono il set usato dal firmware. Davis documenta ufficialmente la banda EU e l\'uso FHSS, non questa specifica sequenza numerica nella scheda commerciale. [D2][R][P]'),
          h2('5.2 Cadenza di trasmissione'),
          P('La specifica Davis indica un intervallo di trasmissione variabile con l\'ID: circa 2,25 s per ID 1 fino a 3 s per ID 8. Il firmware usa 2555 ms come periodo nominale per il proprio inseguimento, valore che va quindi considerato un compromesso implementativo da validare sul campo per ogni ID. [D2][P]'),
          InfoBox('Implicazione pratica', 'Un ricevitore che rimane bloccato su una sola frequenza perde la maggior parte dei frame. Il gateway deve acquisire un canale valido e poi seguire la sequenza di hop, resettando la sincronizzazione quando aumenta il numero di slot mancati.', 'info'),
          PageBreak()]

# 6 RF frame
story += [h1('6. Struttura del frame RF e validazione CRC','s6'),
          P('Il ricevitore SX1276 e configurato in modalita FSK a pacchetto fisso. Il preambolo implementato e 4 x AA, seguito dal sync CB 89. Dopo la ricezione, ogni byte viene normalizzato mediante inversione dei bit prima della decodifica. [R][P]'),
          FrameDiagram(),
          P('Figura 4 - Schema logico del frame da 10 byte usato dal decoder corrente.', 'Captionx'),
          table([
              ['Byte','Uso nel decoder 0.2.0-dev'],
              ['0','Nibble alto = packet type; bit 3 = batteria; bit 2..0 = ID trasmettitore 0..7'],
              ['1','Velocita vento'],
              ['2','Direzione vento'],
              ['3-4','Payload specifico del packet type'],
              ['5','Dato/riservato, incluso nel CRC primario'],
              ['6-7','CRC16-CCITT, MSB first'],
              ['8-9','Campi aggiuntivi/retransmit non ancora validati nella alpha'],
          ], [20*mm,CONTENT_W-20*mm]),
          h2('6.1 CRC16-CCITT'),
          P('Il CRC Davis viene calcolato in software sui byte normalizzati 0..5 con polinomio 0x1021 e valore iniziale 0. Il risultato e confrontato con i byte 6 e 7. Il CRC hardware dell\'SX1276 resta disabilitato.'),
          Preformatted('crc = CRC16_CCITT(bytes[0..5], poly=0x1021, init=0)\nvalid = (crc == (byte6 << 8 | byte7))', styles['Codex']),
          InfoBox('Perche il CRC e importante', 'La sincronizzazione FHSS puo produrre falsi lock o ricezioni parziali. Un CRC software coerente e il primo filtro per distinguere un frame plausibile da rumore o da un pacchetto acquisito sul timing sbagliato.', 'ok'),
          PageBreak()]

# 7 packet types
